#Config file for run.py, containing username, password and api key

SPEECH_TO_TEXT_USERNAME = 'YOUR SPEECH_TO_TEXT USER NAME'
SPEECH_TO_TEXT_PASSWORD = 'YOUR SPEECH_TO_TEXT PASS'
TEXT_TO_SPEECH_USERNAME = 'YOUR TEXT TO SPEECH USER NAME'
TEXT_TO_SPEECH_PASSWORD = 'YOUR TEXT TO SPEECH USER PASS'
CONVERSATION_USERNAME = 'YOUR CONVERSATION USER NAME'
CONVERSATION_PASSWORD = 'YOUR CONVERSATION USER PASS'
WORKSPACE_ID = 'YOUR CONVERSATION WORKSPCE ID'
ALCHEMY_API_KEY  = 'YOUR ALCHEMY_API_KEY'

